version: "3.3"
services:
  node-app:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./node-app:/var/www/html
      # - ./nginx/conf.d/:/etc/nginx/conf.d/
    env_file:
      - ./node-app/.env
    ports:
      - 5500:5000
    networks:
      - api-network
    environment:
      - API_KEY=${API_KEY}
      - STORAGE_BUKET=${STORAGE_BUKET}
      - APP_ID=${APP_ID}
      - AUTH_DOMAIN=${AUTH_DOMAIN}
      - PROJECT_ID=${PROJECT_ID}
      - MEASURMENTID=${MEASURMENTID}
      - MESSAGINGSENDERID=${MESSAGINGSENDERID}
    stdin_open: true
    tty: true

  # nginx:
  #   image: nginx
  #   restart: always
  #   depends_on:
  #     - node-app
  #   env_file:
  #     - ./node-app/.env
  #   ports:
  #     -${NGINX_DOCKER_PORT}:${NGINX_LOCAL_PORT}
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  api-network:
    driver: bridge
